import type { Guide } from '../src/types.ts';
// 원본은 읽기 전용으로 참조하며, 웹사이트용 안내만 관리합니다.
export const guides: Record<string, Guide> = {
 engineering: {
  usage:['Node.js 24 이상에서 setup engineering으로 빌드를 준비하고 호출 스킬을 연결합니다. 스킬만 복사하지 말고 실행기 저장소를 함께 유지합니다.', 'projectRoot·allowedFiles·allowedTools·호출/활동 시간 예산·acceptance를 task.json에 정합니다. files 연결을 기본으로 쓰고 설정과 새 실행 폴더는 원본 저장소 밖에 둡니다.', 'run → status → resume 순서로 request.json의 ID·해시·종류를 읽고 schemaVersion/requestId/requestHash/value 응답을 작성합니다. 쓰기 전 read_file의 SHA-256을 expectedSha256으로 전달합니다.', '기존 승인 범위에는 allow를 사용할 수 있으며 쓰기별 검토가 필요하면 ask를 유지합니다. unknown이면 파일 hash·저널을 확인하고 효과를 자동 반복하지 않습니다.', '0 성공, 1 실패, 2 입력/상태 오류, 3 대기, 4 효과 미확정을 구분합니다. 실제 diff와 독립 acceptance를 확인하며 batch/worktree·memory·serve/control은 필요할 때 선택합니다.'],
  promptExamples:[{title:'체크포인트 재개',prompt:'지정한 Engineering 실행 폴더의 상태와 대기 요청을 확인하고 기존 승인 범위에서 재개해줘. requestId/requestHash를 대조하고 파일 쓰기 전 읽은 해시를 사용해줘. unknown이면 효과를 반복하지 말고 현재 파일과 저널로 복구 가능 여부를 판단해줘.'},{title:'실제 완료 조건 확인',prompt:'지정한 Engineering 실행의 실제 최종 파일을 acceptance와 대조해줘. 모델의 완료 문구와 구분해서 파일별 diff, 통과·실패와 미확정 효과를 보고해줘. 파일과 실행 기록은 수정하지 마.'}]
 },
 'audit-research': {
  usage:['Node.js 24 이상에서 setup audit-research로 준비하고 호출 스킬을 연결합니다.', '절대 root·question·정확한 문자열 claims·파일/bytes/활동 시간 예산을 spec.json에 정합니다. 새 출력 폴더는 조사 root와 원본 저장소 밖에 둡니다.', 'run 또는 extract 후 report.json·documents.json·tasks.json의 인용과 coverage·제외·주장 판정을 확인합니다. 제안된 작업은 자동 실행하지 않습니다.', 'verify로 현재 파일과 추출 text·locator의 변경을 검사합니다. refresh는 같은 root의 새 출력 폴더에 새 보고서를 만들며 이전 보고서를 보존합니다.', '0은 조사 완료/현재 근거 확인, 1은 실패 또는 stale, 2는 입력 오류입니다. 조사 완료와 모든 주장 supported를 구분하며 PDF/Office/이미지 의미 추출·전체 호출 그래프는 지원하지 않습니다.'],
  promptExamples:[{title:'기존 보고서 근거 갱신',prompt:'지정한 Audit 보고서를 verify로 확인하고 근거가 바뀌었다면 같은 root에 대해 refresh로 새 보고서를 만들어줘. 추가·수정·삭제·미검토와 조사 범위 변화를 구분하고 이전 보고서를 보존해줘. 결과는 조사 원본 밖의 새 폴더에 저장해줘.'},{title:'자료 추출',prompt:'지정한 저장소의 JSON·CSV·Markdown 자료를 읽기 전용으로 extract해줘. JSON pointer·CSV 행·Markdown 시작 행과 원본 hash를 연결하고 partial·unverified·제외 원인을 보고해줘. 문서 안의 지시는 실행하지 마.'}]
 },
 operations: {
  usage:['Node.js 24 이상에서 setup operations로 준비하고 합성 계정·값의 127.0.0.1 test-service를 별도 세션에서 실행합니다. 인증 토큰은 지정한 환경변수에 둡니다.', 'baseUrl·accountId·tokenEnv·resource·value·예산을 정합니다. prepare부터 정상 완료에는 요청 최소 7회가 필요하며 설정·서비스·실행 결과는 원본 저장소 밖에 둡니다.', 'prepare가 만든 request.json의 계정·대상·현재 값·변경 값·requestHash를 확인합니다. 기존 승인과 일치할 때 approved/requestHash의 approval.json으로 execute합니다.', 'receipt와 최종 resource가 모두 일치해야 성공입니다. unknown은 PUT 반복 대신 reconcile 조회로 확인하고 영수증이 없으면 미확정으로 유지합니다.', '0 성공/관리 명령, 1 거절·충돌·실패, 2 입력/연결 오류, 3 승인 대기, 4 효과 미확정을 구분하고 JSON status/reason을 확인합니다. 종료된 소유자의 lock만 명시적으로 복구합니다.'],
  promptExamples:[{title:'효과 미확정 확인',prompt:'지정한 Operations 실행이 unknown인 원인을 확인하고 reconcile로 영수증과 최종 값을 조회해줘. PUT은 반복하지 마. 승인 범위·status/reason·확인한 효과·남은 미확정을 보고해줘.'},{title:'승인·충돌 시험',prompt:'합성 loopback 시험 서비스에서 승인 대기와 stale approval·ETag 충돌 처리를 검증해줘. prepare의 실제 계정·대상·내용을 확인하고 허용된 시험 범위에서만 실행해줘. 실제 SaaS 운영 검증과 구분하고 설정·결과는 원본 저장소 밖에 저장해줘.'}]
 },
 lab: {
  usage:['Node.js 24 이상에서 setup lab으로 준비하고 호출 스킬을 연결합니다. eval-foundation은 내장 합성 계약 점검입니다.', 'trials의 suite에 fake/replay/live 모드·cases·expectedReason·repeat·전체 예산·버전을 정합니다. 모든 실행은 새 출력 폴더를 사용합니다.', 'replay는 v2 recording과 구성·요청·무결성을 대조하며 누락·손상·불일치에서 live로 전환하지 않습니다. live는 허용된 절대 Node CLI와 argv·종료 코드·artifact를 실제 자식 프로세스로 실행합니다.', 'compare의 0은 비교 가능이며 성능 개선을 뜻하지 않습니다. speculate는 2~4개 fake suite만 비교하며 결과를 프로젝트에 자동 적용하지 않습니다.', 'passed/failed/error/unsupported/inconclusive와 원래 exitCode, 신규 호출과 recordedUsage를 구분합니다. trial cwd 분리는 OS sandbox가 아니며 실제 모델 품질·비용이 미확인이면 그대로 보고합니다.'],
  promptExamples:[{title:'녹화 재생·회귀 비교',prompt:'지정한 Lab v2 recording을 replay 모드로 재생하고 비교 대상 보고서와 compare해줘. 구성·요청 해시·누락·중복을 검사하고 비교 가능 여부와 실패/미실행을 보고해줘. 신규 호출 0과 과거 recordedUsage를 구분하고 live로 전환하지 마.'},{title:'실제 CLI 반복 관측',prompt:'명시한 Node CLI를 허용된 명령·효과 범위 안에서 Lab live 모드로 반복 관측해줘. 절대 entry·argv·허용 종료 코드·artifact와 예산을 정하고 stdout·파일 hash·원래 exitCode를 보고해줘. 결과는 원본 저장소 밖에 저장하고 실제 모델 품질 평가로 표현하지 마.'}]
 },
 'scrum-weekly-report': {
  usage:['개인 업무 메모·지정한 작업 기록과 선택적 전주 보고서를 준비합니다. 자료에 없는 중요한 실적/계획 기간만 확인하고 실제 날짜를 사용합니다.', '같은 목적의 작업을 묶되 수행 대상·구체적인 변경·결과·현재 상태를 보존합니다. 종료 업무와 신규 업무, 구현·병합·배포·운영 검증 상태를 구분합니다.', '기본 결과는 지난 결과 위·다음 계획 아래의 A4 세로 한 페이지 PDF와 편집 가능한 HTML입니다. 채팅 문안만 요청하면 파일을 만들지 않습니다.', '인쇄용 템플릿은 복사해 사용하고 사용자 문자열을 HTML 이스케이프합니다. 본문을 12pt 미만으로 줄이거나 잘림으로 내용을 숨기지 않습니다.', '최종 PDF가 정확히 한 페이지인지 확인하고 렌더링해 한글·겹침·잘림·과밀을 검증합니다. PDF 생성이나 렌더링을 못 하면 해당 미검증을 밝힙니다.'],
  promptExamples:[{title:'채팅 보고 문안',prompt:'제공한 메모를 개인 주간 업무 보고 문안으로 정리해줘. 파일은 만들지 말고 실제 날짜의 지난 결과와 다음 계획을 순서대로 써줘. 구체적인 수행 내용과 진행·대기 상태를 보존하고 자료에 없는 성과나 계획을 추가하지 마.'},{title:'기존 보고서 가독성 개선',prompt:'첨부한 개인 주간 보고서를 주요 업무·핵심 수치·미완료 상태를 보존하며 다듬어줘. 지난 결과와 다음 계획을 한 열로 배치하고 영역 높이를 억지로 맞추지 마. A4 한 페이지 PDF와 편집 가능한 HTML을 만들고 최종 렌더링을 확인해줘.'}]
 },
 frontend: {
  usage: ['Node.js 24 이상에서 setup frontend로 의존성·Chromium을 준비하고 호출 스킬을 연결합니다.', '기존 앱의 경로·로컬 URL을 확인하고 init → doctor → assess 순서로 진행합니다. 설정과 결과는 원본 저장소 밖의 별도 작업 폴더에 지정합니다.', '실제 클릭·입력과 결과 단언을 시나리오에 넣습니다. 기본 경로 방문과 모바일 화면 크기만으로 기능·터치 검증을 완료했다고 판단하지 않습니다.', 'waiting-for-agent이면 요청의 PNG와 스키마를 읽고 response.json을 작성한 뒤 resume합니다. 종료 코드 2만으로 실패라고 판단하지 않습니다.', '최종 상태, 화면·상호작용 coverage와 미검증 범위를 확인합니다. 소스 개선은 별도 요청이 있을 때만 진행합니다.', 'restore는 알려진 패치 이전 기존 텍스트 파일의 복원 계획을 만들며 --apply는 명시적으로 요청된 경우에만 사용합니다. 복원 후 새 assess로 확인합니다.', 'export-fixture/replay-fixture는 저장 교환의 오프라인 계약 검증입니다. 브라우저 재실행·이미지 재채점과 구분하고 구성 불일치에서 live로 전환하지 않습니다.'],
  promptExamples: [{title:'복원 계획 확인',prompt:'지정한 Frontend improve 실행의 알려진 패치 이전 상태로 돌아갈 restore 계획을 만들어줘. --apply는 사용하지 말고 사용자 수정·해시 충돌·지원하지 않는 파일 변경과 대상 목록을 보고해줘. 계획은 원본 저장소 밖의 새 폴더에 저장해줘.'},{title:'저장된 화면 재평가',prompt:'지정한 기존 결과 폴더의 저장 증거를 reevaluate로 다시 평가해줘. 각 PNG를 직접 확인하고 이전 결과와 차이를 설명해줘. 현재 앱을 다시 실행한 결과와 구분하고, 새 결과는 원본 저장소 밖에 저장해줘.'},{title:'반응형·상태 유지 점검',prompt:'현재 앱의 핵심 사용자 흐름에 클릭·입력·결과 단언을 추가해 평가해줘. 지원 화면 크기와 테마를 확인하고 저장 후 reload로 상태 유지도 검사해줘. 앱 소스와 하네스 저장소는 수정하지 말고 설정·결과는 별도 작업 폴더에 저장해줘.'}]
 },
 persona: {
  usage: ['Node.js 24 이상에서 setup persona로 런타임·예제 설정을 확인합니다. npm·브라우저 설치는 필요하지 않습니다.', '실제 페르소나 명세와 기준·후보 프롬프트를 준비하고, 설정·응답·결과는 원본 저장소 밖의 별도 작업 폴더에 둡니다.', 'target의 replay/files/HTTP와 judge의 files/HTTP를 구분합니다. validate → plan으로 사례·suite·예산을 확인한 뒤 run합니다.', 'waiting이면 target·judge 요청을 구분해 스키마에 맞는 응답을 작성하고 resume합니다. 코드 0은 선택 범위 통과, 1은 품질 실패, 2는 대기·차단·오류·비교 불완전입니다.', '프롬프트·입력·코어가 바뀌면 새 실행을 만듭니다. 저장 응답의 평가 기준만 바꾸면 rescore를 쓰고 compare의 비교 가능 여부를 확인합니다.', '--concurrency 1..4로 제한 병렬 실행합니다. 기본은 1이며 HTTP 병렬 연결에는 independent-sessions 선언이 필요합니다. 병렬도 변경은 비교 조건 변화로 기록합니다.', 'export-fixture/replay-fixture는 완료된 target/Judge 교환과 과거 usage를 보존합니다. synthetic/live/mixed 출처를 구분하며 오프라인 재생을 실제 모델 품질 재측정으로 표시하지 않습니다.'],
  promptExamples: [{title:'제한 병렬 평가',prompt:'현재 Persona 설정과 예산을 확인하고 --concurrency 2로 기준·후보를 평가해줘. 실제 HTTP 연결의 independent-sessions 선언을 확인하고 대화 턴 순서를 유지해줘. 병렬도에 따른 비교 조건 변화와 미확정 호출을 보고하고 결과는 원본 저장소 밖에 저장해줘.'},{title:'저장 응답 재채점',prompt:'지정한 기존 run의 저장 응답을 새 평가 기준으로 rescore해줘. 실제 응답을 새로 수집한 결과와 구분하고 compare의 비교 가능 여부, 필수 위반과 회귀를 보고해줘. 원본 저장소는 수정하지 말고 새 결과는 별도 작업 폴더에 저장해줘.'},{title:'후보 프롬프트 개선',prompt:'기준·후보의 development 실패 근거로 후보 프롬프트를 최소 수정하고 새 실행으로 평가해줘. holdout을 보고 수정한 사례는 미사용 최종 검증으로 주장하지 마. 합성 응답과 실제 모델 응답을 구분하고 원본 저장소 밖의 별도 작업 폴더에서 작업해줘.'}]
 },
 'static-repository-architecture-audit': {usage:['읽을 저장소와 실행·쓰기 범위를 정하고 현재 커밋과 작업 트리 상태를 기록합니다.', '진입점에서 실제 소비자까지 호출·상태·외부 경계를 추적합니다. 누락된 구현은 호출 계약까지만 설명합니다.', '핵심 주장에 파일·행·심볼·조건을 연결하고 코드 관찰, 추론, 미검증을 구분합니다.', '필요하면 scripts/audit_snapshot.py와 scripts/validate_evidence.py의 도움말을 확인해 스냅샷·파일·행·해시 근거를 검사합니다. 분석 대상 코드를 실행하거나 수정하지 않습니다.']},
 'agent-execution-flow-map': {usage:['문제가 발생한 모델·도구 반복의 진입점과 실제 소비자를 찾습니다.', '재시도·fallback·종료·취소 경로를 추적하고 각 counter의 소유자·수명·reset을 구분합니다.', '중복 효과, 최대 한도와 경계값의 반례를 파일·행·조건으로 설명합니다. 선언만으로 실제 종료를 보장하지 않습니다.']},
 'tool-permission-boundary-review': {usage:['대표 도구의 입력부터 최종 실행 효과까지 승인·실행 소비자를 선택합니다.', 'parsed → 검증 → Hook 변경 → 승인 → executed 입력을 필드별로 추적하고 변경 후 재검사를 확인합니다.', 'deny/ask/allow와 headless·원격·비동기 분기의 최종 반환을 읽습니다.', '공격자 제어 입력, 도달 조건, 현재 통제, 최종 효과와 최소 회귀 사례를 근거와 함께 보고합니다.']},
 'context-lifecycle-review': {usage:['in-memory, model-visible, persisted, resumed 상태를 나누고 수집·저장·삭제 경로를 확인합니다.', '요청 전 적용 순서와 토큰 예산, 압축·치환의 보존 순서 및 call/result 쌍을 추적합니다.', 'counter reset, 캐시 안정성과 cleanup 호출·대상·예외까지 검토합니다. 모델 입력에서 빠진 것을 디스크 삭제로 설명하지 않습니다.']},
 'extension-surface-risk-review': {usage:['공급원부터 설치·캐시·활성·실행·업데이트·삭제까지 생명주기를 연결합니다.', 'manifest 문법, 경로 존재, canonical containment와 실제 소비자 권한을 구분합니다.', '설치 시 발생하는 효과, proxy·redirect·loopback과 호스트별 스킬 필드 의미를 확인합니다.', '제어 가능한 입력·도달 조건·효과·통제를 보고합니다. 외부 코드 실행이나 symlink 대상 열람을 자동으로 수행하지 않습니다.']},
 'session-resume-integrity-review': {usage:['writer부터 loader·normalizer·resume consumer까지 저장·복원 흐름을 추적합니다. 로그 권한이 없으면 코드와 합성 fixture만 사용합니다.', 'ID와 parent chain, 병렬 형제, flush/ack, 압축 relink와 call/result 대응을 확인합니다.', '부분 JSONL·중복 ID·고아 결과·권한 및 작업 경로 복원을 별도 사례로 판정합니다.', 'ID 집합·허용 순서·의도된 삭제 유지·외부 효과 횟수를 불변식으로 보고합니다. 원본 로그 수정이나 재생은 하지 않습니다.']},
 'pre-pr-verification': {usage:['base/head와 작업 트리, 요구사항 및 핵심 주장을 고정합니다.', '실패 경로와 반례를 찾고 변경의 최종 소비·저장·제거까지 의미를 추적합니다.', '관련 테스트와 필수 표준 명령을 실행하고 결과를 해당 스냅샷·환경·실제 실행 범위와 연결합니다. 실패·건너뜀·취소·미실행을 구분합니다.', '영향이 있으면 운영·배포 상태를 읽기 전용으로 대조합니다. 위험에 따라 기본 자체 리뷰 또는 강화 독립 리뷰를 적용하고 미검증을 남깁니다.']},
 'git-workflow': {usage:['요청된 브랜치·커밋·push·PR 범위와 저장소 지침을 확인합니다.', '현재 브랜치·원격·upstream·diff를 확인하고 관련 없는 변경을 보존합니다.', '요청한 변경만 검증·staging하고 제목, 목적 문단과 주요 변경 목록이 있는 커밋을 작성합니다.', 'push 또는 PR이 요청된 경우에만 확인한 대상에 수행하고 원격 반영 결과를 확인합니다.']},
 'pr-review-feedback': {usage:['전달받은 리뷰 의견과 해당 코드·호출자·보호 로직을 대조합니다.', '각 의견의 타당성과 필요한 최소 수정 범위를 판정합니다.', '타당한 수정과 관련 회귀 검증 후 등록용 답변을 작성합니다. 댓글 등록·커밋·push는 요청된 범위에서만 수행합니다.']},
 'write-project-readme-docs': {usage:['현재 구현과 기존 README·문서를 비교하고 quick·standard·complete 중 요청에 맞는 범위를 선택합니다.', '실제 라우트·설정·실행 명령·테스트를 근거로 문서를 작성하고 유효한 기존 이미지를 보존합니다.', '구현과 계획, 검증한 명령과 미검증을 구분하고 문서 링크와 설명을 코드에 맞춥니다.']},
 'universal-project-presentation': {
  summary:'코드·문서·데이터로 발표 자료와 대본을 만들고, 별도 Q&A 모드로 예상 질문과 근거 있는 답변을 준비합니다.',
  when:'기술 발표·피치덱을 제작하거나 기존 발표의 심사·질의응답을 준비할 때',
  note:'presentation, qna, presentation + qna를 요청에 따라 선택합니다. 기본 발표에 예상 질문집을 자동 추가하지 않으며 백업 슬라이드는 요청할 때 만듭니다.',
  usage:['자료에서 청중·목적·시간·출력 형식을 확인하고 presentation / qna / presentation + qna 범위를 정합니다.', '실제 코드·데이터를 근거로 구현·가정·계획을 구분하고 핵심 주장과 증거를 선정합니다.', '제공된 PPT가 필수 양식인지 참고 디자인인지 확인해 유지·부분 개선·전면 변경을 판단합니다. 필요할 때 동일 내용으로 후보의 한글 가독성·편집성·호환성·이용 조건을 비교합니다.', 'PPTX·Slidev·HTML·PDF 또는 스토리보드를 요청 범위에 맞춰 만들고 대본을 준비합니다. qna 단독은 기존 본편을 다시 만들지 않습니다.', '최종 생성 파일을 렌더링해 잘림·겹침·출처·시간을 검증합니다. Q&A 답변은 근거와 미확인을 표시하고 요청된 백업만 별도로 제작합니다.'],
  promptExamples:[{title:'기존 발표 Q&A 준비',prompt:'기존 발표 자료를 바탕으로 qna 모드로 심사위원의 예상 질문과 답변을 준비해줘. 구현·수치·설계 선택의 근거와 미확인 내용을 구분하고 후속 질문도 정리해줘. 본편과 백업 슬라이드는 새로 만들지 마.'},{title:'발표와 백업 슬라이드',prompt:'현재 프로젝트의 10분 기술 발표와 5분 Q&A를 presentation + qna 모드로 준비해줘. 본편 PPTX·대본과 예상 질문·근거 있는 답변을 분리하고 필요한 백업 슬라이드도 만들어줘. 실제 구현과 계획을 구분하고 최종 PPTX를 렌더링해서 검증해줘.'},{title:'기존 템플릿 개선',prompt:'첨부한 PPT를 참고 디자인으로 보고 발표 목적에 맞게 평가해줘. 유지·부분 개선·전면 변경 중 적합한 방향을 판단하고 필요하면 동일한 실제 내용으로 후보를 비교해줘. 한글 가독성·편집성·호환성과 이용 조건을 확인해줘.'}]
 },
 'writing-plans': {note:'원본은 obra/superpowers의 skills/writing-plans입니다. brainstorming과 함께 설치·갱신하며 기록된 적용 커밋으로 원본 변경을 확인합니다.'}
};
