import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, ArrowLeft, ArrowRight, BookOpen, Books, Check, CheckCircle, Code, Copy, Cube, DotsThree, GitBranch, GithubLogo, Heart, Info, List, MagnifyingGlass, Monitor, Moon, Rows, SquaresFour, Star, Sun, Terminal, Wrench, X, Clock, ArrowsClockwise, WarningCircle, Sparkle, CaretRight } from '@phosphor-icons/react';
import catalog from './data/catalog.json';
import updateData from './data/updates.json';
import type { Tool, Update, Workflow } from './types';
const tools=catalog.tools as unknown as Tool[];
const rawUpdates=updateData.tools as unknown as Record<string,Update>;
const updates=Object.fromEntries(tools.filter(t=>rawUpdates[t.id]?.snapshotHash===t.snapshotHash).map(t=>[t.id,rawUpdates[t.id]]));
const workflows=catalog.workflows as Workflow[];
const kindLabels={harness:'하네스',custom:'커스텀 스킬',external:'외부 스킬'};
const categories=[...new Set(tools.map(t=>t.category))];
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(v)):'아직 확인하지 않음';
function readSaved<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}}
function statusOf(update?:Update){if(!update)return {label:'확인 전',tone:'neutral'};if(Date.now()-Date.parse(update.checkedAt)>72*3600_000)return {label:'확인 오래됨',tone:'neutral'};return {current:{label:'변경 없음',tone:'success'},changed:{label:'업데이트 있음',tone:'warning'},unknown:{label:update.baseline?'원본 경로 미확인':'설치 버전 미확인',tone:'neutral'},error:{label:'확인 실패',tone:'danger'}}[update.status];}
function ToolIcon({tool,size=24}:{tool:Tool;size?:number}){const Icon=tool.kind==='harness'?(tool.id==='frontend'?Monitor:Sparkle):tool.category==='Git·리뷰'?GitBranch:tool.category==='문서·발표'?BookOpen:tool.category==='글쓰기'?Books:tool.category==='환경·토큰'?Terminal:tool.category==='프론트엔드'?SquaresFour:Code;return <span className={`tool-icon ${tool.kind}`}><Icon size={size} weight="duotone"/></span>;}
function Badge({tool}:{tool:Tool}){const status=statusOf(updates[tool.id]);return tool.kind==='external'?<span className={`status ${status.tone}`}><i/>{status.label}</span>:<span className="status neutral">직접 관리</span>;}
function CopyButton({text,label='복사',onCopy}:{text:string;label?:string;onCopy:(s:string)=>void}){return <button className="button small" onClick={async()=>{try{await navigator.clipboard.writeText(text);onCopy('클립보드에 복사했습니다.');}catch{onCopy('복사하지 못했습니다. 텍스트를 선택해 직접 복사해 주세요.');}}}><Copy size={15}/>{label}</button>;}
export default function App(){
 const [section,setSection]=useState('all');const [query,setQuery]=useState('');const [category,setCategory]=useState('전체 분야');
 const [view,setView]=useState<'grid'|'list'>(()=>readSaved('toolkit-view','grid'));
 const [favorites,setFavorites]=useState<string[]>(()=>{const v=readSaved<unknown>('toolkit-favorites',[]);return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];});
 const [dark,setDark]=useState(()=>readSaved('toolkit-dark',false));const [mobileMenu,setMobileMenu]=useState(false);const [toast,setToast]=useState('');
 const readHash=()=>{try{return decodeURIComponent(location.hash.slice(1));}catch{return '__invalid';}};
 const [selected,setSelected]=useState(readHash);const [promptMode,setPromptMode]=useState('기본');const [context,setContext]=useState('');
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const fn=()=>{setSelected(readHash());setPromptMode('기본');setContext('');window.scrollTo(0,0);};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 useEffect(()=>{try{localStorage.setItem('toolkit-favorites',JSON.stringify(favorites));localStorage.setItem('toolkit-view',JSON.stringify(view));localStorage.setItem('toolkit-dark',JSON.stringify(dark));}catch{}document.documentElement.dataset.theme=dark?'dark':'light';},[favorites,view,dark]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();if(location.hash)location.hash='';setSection('all');setTimeout(()=>searchRef.current?.focus(),0);}if(e.key==='Escape'){setMobileMenu(false);if(location.hash)location.hash='';}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[]);
 const selectSection=(next:string)=>{location.hash='';setSection(next);setCategory('전체 분야');setQuery('');setMobileMenu(false);};
 const toggleFavorite=(id:string)=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const filtered=useMemo(()=>tools.filter(t=>(section==='all'||section==='favorites'&&favorites.includes(t.id)||section==='updates'&&t.kind==='external'||t.kind===section)&&(category==='전체 분야'||t.category===category)&&`${t.title} ${t.id} ${t.callName} ${t.summary} ${t.when} ${t.note} ${t.promptExamples?.map(p=>p.title).join(' ')??''} ${t.category} ${t.source.repo}`.toLocaleLowerCase().includes(query.toLocaleLowerCase().trim())),[section,category,query,favorites]);
 const selectedTool=tools.find(t=>t.id===selected);
 const changed=tools.filter(t=>t.kind==='external'&&updates[t.id]?.status==='changed').length;
 const sectionTitle=section==='all'?'나의 도구 라이브러리':section==='favorites'?'즐겨찾는 도구':section==='updates'?'외부 스킬 업데이트':section==='workflows'?'무엇부터 시작할까요?':kindLabels[section as keyof typeof kindLabels];
 const nav=[{id:'all',label:'모든 도구',Icon:SquaresFour,count:tools.length},{id:'favorites',label:'즐겨찾기',Icon:Star,count:favorites.length},{id:'workflows',label:'작업별 가이드',Icon:GitBranch,count:null},{id:'updates',label:'업데이트',Icon:ArrowsClockwise,count:changed||null}];
 function renderCard(tool:Tool){return <article className={`tool-card ${view}`} key={tool.id}>
  <div className="card-top"><ToolIcon tool={tool}/><span className={`kind ${tool.kind}`}>{kindLabels[tool.kind]}</span><button className={`icon-button favorite ${favorites.includes(tool.id)?'active':''}`} aria-label={`${tool.title} 즐겨찾기 ${favorites.includes(tool.id)?'해제':'추가'}`} aria-pressed={favorites.includes(tool.id)} onClick={()=>toggleFavorite(tool.id)}><Star weight={favorites.includes(tool.id)?'fill':'regular'} size={19}/></button></div>
  <div className="card-body"><a className="card-title" href={`#${tool.id}`}>{tool.title}<ArrowUpRight size={17}/></a><span className="tool-slug">{tool.callName}</span><p>{tool.summary}</p><div className="use-case"><span>이럴 때</span> {tool.when}</div></div>
  <div className="card-bottom"><span className="category-tag">{tool.category}</span><Badge tool={tool}/></div>
  <div className="card-actions"><a href={`#${tool.id}`}>사용법 보기<CaretRight size={14}/></a><CopyButton text={tool.prompt} label="프롬프트" onCopy={setToast}/></div>
 </article>;}
 function renderDetail(tool:Tool){const update=updates[tool.id];const sourcePath=tool.kind==='external'?(update?.path??(tool.source.paths?.length===1?tool.source.paths[0]:'')):tool.source.local;
 const sourceUrl=`https://github.com/${tool.source.repo}${sourcePath?`/tree/${tool.source.baseline??'HEAD'}/${sourcePath}`:''}`;
 const finalPrompt=tool.prompt+(promptMode==='상세'?'\n\n작업 전에 관련 파일과 지침을 확인하고, 확인된 사실과 가정을 구분해줘. 결과에는 수행 범위, 주요 근거, 검증 방법과 남은 제약을 포함해줘.':'')+(context.trim()?`\n\n추가 맥락:\n${context.trim()}`:'');
 return <div className="detail"><button className="text-button" onClick={()=>location.hash=''}><ArrowLeft size={17}/>목록으로</button><div className="detail-heading"><ToolIcon tool={tool} size={32}/><div><span className={`kind ${tool.kind}`}>{kindLabels[tool.kind]} · {tool.category}</span><h1>{tool.title}</h1><span className="tool-slug">{tool.callName}</span></div><button className={`button ${favorites.includes(tool.id)?'selected':''}`} onClick={()=>toggleFavorite(tool.id)}><Star weight={favorites.includes(tool.id)?'fill':'regular'}/>즐겨찾기</button></div><p className="detail-summary">{tool.summary}</p>
 <div className="detail-columns"><div><section className="detail-section"><h2>언제 사용하나요?</h2><p>{tool.when}</p><div className="note"><Info size={18}/><span>{tool.note}</span></div></section><section className="detail-section"><h2>사용 순서</h2><ol className="steps">{tool.usage.map(s=><li key={s}>{s}</li>)}</ol><div className="code-heading"><span>로컬 준비 명령</span><CopyButton text={tool.commands.join('\n')} onCopy={setToast}/></div><pre>{tool.commands.join('\n')}</pre><p className="helper">기본 경로는 ~/agent입니다. 다른 위치에 보관했다면 경로를 바꿔주세요. Claude Code는 link-claude.sh를 사용합니다.</p></section>
 <section className="detail-section prompt-section"><div className="section-top"><h2>추천 프롬프트</h2><span className="tag">복사해서 바로 시작</span></div><div className="segmented">{['기본','상세'].map(v=><button className={promptMode===v?'active':''} onClick={()=>setPromptMode(v)} key={v}>{v}</button>)}</div><label className="context-label" htmlFor="context">프로젝트나 원하는 결과를 덧붙여 보세요 <span>선택</span></label><textarea id="context" value={context} onChange={e=>setContext(e.target.value)} placeholder="예: 결제 화면을 모바일 중심으로 검증하고 싶어요." rows={2}/><pre className="prompt-preview">{finalPrompt}</pre><CopyButton text={finalPrompt} label="프롬프트 복사" onCopy={setToast}/></section>{tool.promptExamples?.length ? <section className="detail-section"><h2>상황별 추천 프롬프트</h2>{tool.promptExamples.map(example=><div key={example.title} className="prompt-example"><h3>{example.title}</h3><pre className="prompt-preview">{example.prompt}</pre><CopyButton text={example.prompt} label={`${example.title} 복사`} onCopy={setToast}/></div>)}</section>:null}</div>
 <aside className="detail-aside"><section className="detail-section"><h2>출처와 적용 상태</h2><Badge tool={tool}/><dl><dt>원본 저장소</dt><dd><a href={`https://github.com/${tool.source.repo}`} target="_blank" rel="noreferrer">{tool.source.repo}<ArrowUpRight size={13}/></a></dd><dt>마지막 로컬 동기화</dt><dd>{date(tool.syncedAt)}</dd><dt>등록된 적용 기준</dt><dd><code>{tool.source.baseline?.slice(0,12)||'기록 없음'}</code></dd>{tool.kind==='external'&&<><dt>원본 확인 시각</dt><dd>{date(update?.checkedAt)}</dd><dt>개인 수정</dt><dd>{update?.personal==='modified'?'원본과 로컬 차이 있음':update?.personal==='same'?'차이 없음':'확인되지 않음'}</dd><dt>비교 결과</dt><dd>{update?.reason||'현재 로컬 스냅샷의 원본 비교가 필요합니다.'}</dd></>}</dl><a className="button full" href={sourceUrl} target="_blank" rel="noreferrer"><GithubLogo size={17}/>원본 보기<ArrowUpRight size={14}/></a>{update?.latest&&tool.source.baseline&&<a className="text-button" target="_blank" rel="noreferrer" href={`https://github.com/${tool.source.repo}/compare/${tool.source.baseline}...${update.latest}`}>원본 커밋 비교<ArrowUpRight size={14}/></a>}<p className="helper">내 적용 상태는 마지막으로 동기화한 기록입니다. Mac의 현재 설치 상태를 실시간 조회하지 않습니다.</p></section>
 {update?.changes.length? <section className="detail-section"><h2>변경된 파일 <span className="muted">{update.changes.length}</span></h2><ul className="file-changes">{update.changes.slice(0,15).map(c=><li key={c.path}><span>{c.type==='added'?'+':c.type==='removed'?'−':'~'}</span><code>{c.path}</code></li>)}</ul>{update.changes.length>15&&<p className="helper">나머지는 원본 커밋 비교에서 확인하세요.</p>}</section>:null}
 <section className="detail-section"><h2>함께 쓰면 좋은 도구</h2>{tools.filter(t=>t.id!==tool.id&&t.category===tool.category).slice(0,3).map(t=><a className="related" href={`#${t.id}`} key={t.id}><ToolIcon tool={t} size={18}/><span>{t.title}</span><CaretRight size={15}/></a>)}</section></aside></div></div>;}
 return <div className="app"><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();document.getElementById('main-content')?.scrollIntoView();}}>본문으로 이동</a>{mobileMenu&&<button className="nav-scrim" aria-label="메뉴 닫기" onClick={()=>setMobileMenu(false)}/>}
 <aside className={`sidebar ${mobileMenu?'open':''}`}><a href="#" className="brand" onClick={()=>selectSection('all')}><span className="brand-mark"><Code weight="bold" size={23}/></span><span>agent-toolkit<small>Personal workspace</small></span></a><div className="workspace-label"><span className="avatar">L</span><div>나의 작업 공간<small>LeeTheY</small></div><span className="private-tag">Private</span></div><nav aria-label="주요 메뉴"><p className="nav-label">라이브러리</p>{nav.map(({id,label,Icon,count})=><button key={id} className={`nav-item ${section===id&&!selected?'active':''}`} onClick={()=>selectSection(id)}><Icon size={19} weight={section===id?'duotone':'regular'}/><span>{label}</span>{count!==null&&<span className="nav-count">{count}</span>}</button>)}<p className="nav-label second">도구 유형</p>{(['harness','custom','external'] as const).map(kind=><button key={kind} className={`nav-item ${section===kind&&!selected?'active':''}`} onClick={()=>selectSection(kind)}>{kind==='harness'?<Monitor size={19}/>:kind==='custom'?<Wrench size={19}/>:<Cube size={19}/>}<span>{kindLabels[kind]}</span><span className="nav-count">{tools.filter(t=>t.kind===kind).length}</span></button>)}</nav><div className="sidebar-bottom"><div className="local-note"><span className="connection-dot"/>로컬에서 모은 나의 도구<p>두 저장소의 도구를<br/>한곳에서 찾아보세요.</p></div><a href="https://github.com/LeeTheY/agent-toolkit" target="_blank" rel="noreferrer"><GithubLogo size={18}/>GitHub 저장소<ArrowUpRight size={14}/></a></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="메뉴 열기" onClick={()=>setMobileMenu(true)}><List size={22}/></button><Books size={18}/><span>라이브러리</span><CaretRight size={13}/><strong>{selectedTool?selectedTool.title:section==='all'?'모든 도구':sectionTitle}</strong></div><div className="top-actions"><span className="private-label"><span className="connection-dot"/>개인 작업 공간</span><button className="icon-button" aria-label={dark?'밝은 테마':'어두운 테마'} onClick={()=>setDark(!dark)}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button><span className="avatar small-avatar">L</span></div></header>
 <main id="main-content" tabIndex={-1}>{selected?(selectedTool?renderDetail(selectedTool):<div className="empty-state"><WarningCircle size={40}/><h1>도구를 찾을 수 없습니다.</h1><button className="button" onClick={()=>location.hash=''}>목록으로 돌아가기</button></div>):<>
 <div className="page-heading"><div><div className="heading-eyebrow">나만의 에이전트 도구함</div><h1>{sectionTitle}</h1><p>{section==='updates'?'원본의 변화와 내가 적용한 버전을 구분해서 확인하세요.':section==='favorites'?'자주 사용하는 도구를 가까이에 모아두세요.':section==='workflows'?'하려는 작업에 맞춰 도구를 순서대로 활용해 보세요.':'필요한 도구를 찾고, 프롬프트 하나로 작업을 시작하세요.'}</p></div><span className="collection-label"><Books size={17}/>{tools.length}개의 도구</span></div>
 {section==='all'&&<div className="intro-panel"><div className="intro-copy"><span className="intro-kicker"><Terminal size={17}/>내 작업에 맞는 도구, 한곳에</span><h2>만드는 방법부터<br/>잘 만들었는지 확인하는 방법까지.</h2><p>하네스와 스킬의 사용법을 살펴보고,<br/>지금 필요한 프롬프트를 가져가세요.</p><button onClick={()=>selectSection('workflows')}>작업별 가이드 보기<ArrowRight size={17}/></button></div><div className="intro-tools"><div className="mini-window"><div className="window-bar"><span/><span/><span/><code>my-toolkit</code></div><div className="stack-item"><span className="stack-icon"><Monitor size={22}/></span><div><strong>Harnesses</strong><small>실행하고, 평가하고, 검증하기</small></div><b>{String(tools.filter(t=>t.kind==='harness').length).padStart(2,'0')}</b></div><div className="stack-item"><span className="stack-icon"><Wrench size={22}/></span><div><strong>Custom skills</strong><small>내 작업 방식으로 만든 스킬</small></div><b>{tools.filter(t=>t.kind==='custom').length}</b></div><div className="stack-item"><span className="stack-icon"><Cube size={22}/></span><div><strong>External skills</strong><small>좋은 도구를 모아 나답게 활용하기</small></div><b>{tools.filter(t=>t.kind==='external').length}</b></div></div></div></div>}
 {section==='workflows'?<div className="workflow-grid">{workflows.map(w=><article className="workflow-card" key={w.id}><GitBranch size={24}/><h2>{w.title}</h2><p>{w.description}</p><ol>{w.steps.map(id=>{const t=tools.find(x=>x.id===id)!;return <li key={id}><a href={`#${id}`}><ToolIcon tool={t} size={18}/>{t.title}<ArrowUpRight size={15}/></a></li>;})}</ol></article>)}</div>:<>
 {section==='updates'&&<div className="update-explainer"><Info size={21}/><div><strong>업데이트 확인과 설치는 별개예요.</strong><p>스킬 폴더의 파일을 등록된 원본 커밋과 비교합니다. 개인 수정은 따로 표시하며, 외부 스킬을 자동으로 덮어쓰지 않습니다.</p><span>최근 확인: {date(updateData.checkedAt)}</span><a href="https://github.com/LeeTheY/agent-toolkit/actions/workflows/check-updates.yml" target="_blank" rel="noreferrer">GitHub에서 다시 확인<ArrowUpRight size={13}/></a></div></div>}
 <div className="catalog-header"><h2>{section==='all'?'모든 도구':section==='updates'?'외부 스킬 상태':sectionTitle}<span>{filtered.length}</span></h2><div className="view-switch" aria-label="보기 방식"><button className={view==='grid'?'active':''} aria-label="카드 보기" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><SquaresFour size={18}/></button><button className={view==='list'?'active':''} aria-label="목록 보기" aria-pressed={view==='list'} onClick={()=>setView('list')}><Rows size={18}/></button></div></div>
 <div className="search-row"><div className="search-box"><MagnifyingGlass size={20}/><input ref={searchRef} aria-label="도구 검색" placeholder="이름, 하고 싶은 작업, 키워드로 검색..." value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button className="icon-button" aria-label="검색 지우기" onClick={()=>setQuery('')}><X size={16}/></button>:<kbd>⌘ K</kbd>}</div><select aria-label="분야 선택" value={category} onChange={e=>setCategory(e.target.value)}>{['전체 분야',...categories].map(c=><option key={c}>{c}</option>)}</select></div>
 {['all','harness','custom','external'].includes(section)&&<div className="type-tabs">{[{id:'all',label:'전체',count:tools.length},{id:'harness',label:'하네스',count:tools.filter(t=>t.kind==='harness').length},{id:'custom',label:'커스텀',count:tools.filter(t=>t.kind==='custom').length},{id:'external',label:'외부',count:tools.filter(t=>t.kind==='external').length}].map(t=><button className={section===t.id?'active':''} onClick={()=>selectSection(t.id)} key={t.id}>{t.label}<span>{t.count}</span></button>)}</div>}
 {filtered.length?<div className={`catalog-grid ${view==='list'?'list-view':''}`}>{filtered.map(renderCard)}</div>:<div className="empty-state"><MagnifyingGlass size={36}/><h2>{section==='favorites'&&!query?'즐겨찾는 도구를 모아보세요.':'검색 결과가 없습니다.'}</h2><p>{section==='favorites'?'도구의 별표를 누르면 이곳에 표시됩니다.':'다른 검색어를 입력하거나 분야 필터를 해제해 보세요.'}</p><button className="button" onClick={()=>{if(section==='favorites')selectSection('all');else{setQuery('');setCategory('전체 분야');}}}>{section==='favorites'?'도구 둘러보기':'검색 초기화'}</button></div>}
 </>}
 <footer><span><CheckCircle size={14}/>로컬 카탈로그 · {date(catalog.syncedAt)}</span><span>나의 도구, 나의 작업 방식.</span></footer></>}</main></div>{toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}</div>;
}
